### ISSUE TITLE
Publishing darcula on maven central

### ISSUE THREAD

**Issue by dpolivaev** [ice1k/darcula#1]
Hello,

because bintray services are deprecated and not available from the next month and because my project freeplane needs darcula I have published it on maven central today. For doing so I had to change the group to the group where I am allowed to publish artifacts from com.bulenkov to org.freeplane.bulenkov. The changes are contained in my commit 
https://github.com/freeplane/darcula/commit/47b41796f07ed2ac5e88425b70feeff2ef39cc15

and the artifact is available at 

https://repo1.maven.org/maven2/org/freeplane/bulenkov/darcula/2018.2/

I am just letting you know and I want to thank you for preparing the artifact for publishing.

Regards,
Dimitry

**Comment by ice1000** [comment]
Thanks for letting me know!

**Comment by ice1000** [comment]
Also thank you for crediting me in the pom file😋
